version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Логин для входа в pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin          # Пароль для входа в pgAdmin
    ports:
      - "5050:80"  # Открываем порт для pgAdmin
    depends_on:
      - postgres

  minio:
    image: minio/minio
    container_name: minio
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: MINIO_ROOT_PASSWORD
      MINIO_SERVER_URL: "http://0.0.0.0:9000"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  minio_data:
